#! /usr/bin/bash
blue="\e[34m"
reset="\e[0m"
green="\e[32m"
yellow="\e[33m"

q="$blue[$yellow?$blue]$reset"
p="$blue[$green+$blue]$reset"

echo -en "$q What is your AUR helper? "
read aur

echo -e "$p Installing AwesomeWM."
if ! command -v awesome $> /dev/null; then
    $aur -S --noconfirm awesome-git
fi
echo -e "$p AwesomeWM successfully installed"

echo -e "$p Installing dependencies"
commands=(picom rofi mpd mpc feh pulseaudio scrot redshift)
for cmd in "${commands[@]}"; do
    if ! command -v "$cmd" &> /dev/null; then
        echo -e "$p Installing $cmd"
        $aur -S --noconfirm "$cmd"
    fi
    echo -e "$p $cmd successfully installed."
done

echo -e "$p Installing alsa-utils."
if ! command -v amixer &> /dev/null; then
    $aur -S --noconfirm alsa-utils
fi
echo -e "$p alsa-utils successfully installed."

echo -e "$p Installing i3lock-fancy."
if ! command -v i3lock-fancy &> /dev/null; then
    $aur -S --noconfirm i3lock-fancy-git
fi
echo -e "$p i3lock-fancy successfully installed."

echo "$q Do you want to enable the system services"
select o in "Yes" "No"; do
    case o in
        "Yes")
            systemctl --user enable mpd.service
            systemctl --user start mpd.service
            systemctl enable acpid.service
            systemctl start acpid.service
            break;;
        "No")
            break;;
    esac
done

echo "$p Installing AwesomeWM config file"
echo -en "$q Do you want to create a backup for your awesome config (y/N)?"
read b
case $b in
    "Yy")
        echo "$p Creating a backup"
        [ -e ~/.config/awesome ] && mv ~/.config/awesome ~/.config/awesome-backup-"$(date +%Y.%m.%d-%H.%M.%S)"
        echo "$p Successfully create a backup"
        break;;
    "Nn")
        rm -rf ~/.config/awesome
        break;;
esac
cp -r awesome ~/.config/awesome
echo "$p AwesomeWM config successfully installed"